### ISSUE TITLE
Broken modules

### ISSUE THREAD

**Issue by rosieks** [arifsetiawan/flatten#12]
I just run flatten-packages in order to prevent too long path and my gulp script stop working. There are commands to reproduce this case:

    yo gulp-angular   // keep default options
    gulp build        // all works properly
    flatten-packages
    gulp build        // node print some error

While running gulp second time I receive the following error:

    E:\projects\a2\node_modules\karma\lib\middleware\runner.js:11
    var json = require('connect').json();
                                  ^
    TypeError: undefined is not a function
        at Object.<anonymous> (E:\projects\a2\node_modules\karma\lib\middleware\runner.js:11:31)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (E:\projects\a2\node_modules\karma\lib\web-server.js:7:24)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

**Comment by arifsetiawan** [comment]
I have reproduced the issue. 
I think it happens because connect version `2.29.2` used by karma is replaced with newer version `3.3.5` during flattening process. And its introduced breaking changes where all connect middlewares are not included by default.

**Comment by arifsetiawan** [comment]
Issue #13
